def execute_code(code, df):

    # Block unsafe operations
    forbidden = [
        "import ",
        "os.",
        "sys.",
        "subprocess",
        "open(",
        "__",
        "eval(",
        "exec(",
        "write(",
        "read("
    ]

    for word in forbidden:
        if word in code:
            return f"Unsafe code detected: {word}"

    local_vars = {"df": df}

    try:

        # Execute generated code
        exec(code, {}, local_vars)

        # Extract result safely
        result = local_vars.get("result", None)

        if result is None:
            return "No result generated by the analysis code."

        return result

    except Exception as e:
        return f"Code execution error: {str(e)}"